### PR TITLE
add: Updated tagservice to read from test_images dynamically

### PR DESCRIPTION
**Pull request by kmcdon10**
Updating the code to read from the test_images file dynamically so people can experiment with it by adding images, without having to rename them or add to the list

### CODE REVIEW

**Review by EdRW — APPROVED** [review]
One issue I was having is that the system pathing changes relative to where tagger.py is called from. As in being called from the Django project root vs calling from the tagservice folder. Just something to note if you have any issues when loading the image files from the test_images folder.

**Comment by kmcdon10** [comment]
I've been working on trying to add tests to the project, and I suspect I'm running into that same issue

**Comment by EdRW** [comment]
Yeah, I think you'll have to make a change to the import statement at the top of tagger.py for the labelmap util. Also to the import at the top of the label map util for the string label map pb. Adding "from . import" might help.

**Comment by kmcdon10** [comment]
Since this is technically my pull request I can't actually approve it, but it looks good to me. Feel free to merge it whenever you see fit

**Comment by EdRW** [comment]
I just noticed that this was a pretty weird branch merge.  I think the commit
add: Updated tagservice to read from test_images dynamically 
was actually done on the branch: feature/sprint2-object-detector
I dont think there were any commits in this branch before the merge.

**Pull request merged**
